version: '3'

networks:
  kokdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: kokdesk/kokdesk-server:latest
    command: hbbs -r kokdesk.example.com:21117
    volumes:
      - ./hbbs:/root
    networks:
      - kokdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: kokdesk/kokdesk-server:latest
    command: hbbr
    volumes:
      - ./hbbr:/root
    networks:
      - kokdesk-net
    restart: unless-stopped
